import React from "react";
import "../styles/FAQs.css";

const FAQ = () => {
  const faqs = [
    {
      question: "What is CsGpt?",
      answer: "CsGpt is an AI-powered educational platform focused on helping users learn computer science concepts deeply through explanations, examples, and interview questions."
    },
    {
      question: "Is this tool free to use?",
      answer: "Yes! The platform is currently free to use for academic and interview preparation."
    },
    {
      question: "Which topics does CsGpt cover?",
      answer: "It covers OS, DBMS, CN, DSA, OOP, Web Tech, System Design, DevOps, Programming Languages like C, C++, Java, Python, JavaScript, and more."
    },
    {
      question: "How are responses generated?",
      answer: "Responses are generated by Gemini AI based on structured prompts designed to deliver in-depth theory, code in multiple languages, and 25+ interview questions."
    }
  ];

  return (
    <div className="info-section">
      <h2>Frequently Asked Questions</h2>
      <ul className="faq-list">
        {faqs.map((faq, idx) => (
          <li key={idx}>
            <h4>{faq.question}</h4>
            <p>{faq.answer}</p>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default FAQ;
