import React, { useState } from "react";
import "../styles/FAQs.css";

const FAQ = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const faqs = [
    {
      question: "What is CsGpt?",
      answer: "CsGpt is an AI-powered educational platform focused on helping users learn computer science concepts deeply through explanations, examples, and interview questions."
    },
    {
      question: "Is this tool free to use?",
      answer: "Yes! The platform is currently free to use for academic and interview preparation."
    },
    {
      question: "Which topics does CsGpt cover?",
      answer: "It covers OS, DBMS, CN, DSA, OOP, Web Tech, System Design, DevOps, Programming Languages like C, C++, Java, Python, JavaScript, and more."
    },
    {
      question: "How are responses generated?",
      answer: "Responses are generated by Gemini AI based on structured prompts designed to deliver in-depth theory, code in multiple languages, and 25+ interview questions."
    }
  ];

  const toggleFAQ = (index) => {
    setActiveIndex(prevIndex => (prevIndex === index ? null : index));
  };

  return (
    <div className="faq-container">
      <h2>Frequently Asked Questions</h2>
      <ul className="faq-list">
        {faqs.map((faq, idx) => (
          <li
            key={idx}
            className={`faq-item ${activeIndex === idx ? "active" : ""}`}
            onClick={() => toggleFAQ(idx)}
          >
            <div className="faq-question">
              {faq.question}
              <span className="arrow">{activeIndex === idx ? "▲" : "▼"}</span>
            </div>
            {activeIndex === idx && (
              <div className="faq-answer">{faq.answer}</div>
            )}
          </li>
        ))}
      </ul>
    </div>
  );
};

export default FAQ;
